<?php

namespace Database\Seeders;

use App\Models\TcgCardCatalog;
use Illuminate\Database\Seeder;

class DragonBallCardsSeeder extends Seeder
{
    public function run(): void
    {
        $sets = [
            // BT1 - Dawn of the Z-Legends
            'Dawn of the Z-Legends' => [
                ['BT1-001', 'Son Goku', 'Leader', 'Super Rare'],
                ['BT1-002', 'Son Goku, the Awakened Power', 'Character', 'Special Rare'],
                ['BT1-003', 'Bulma', 'Character', 'Common'],
                ['BT1-004', 'Krillin', 'Character', 'Common'],
                ['BT1-005', 'Tien Shinhan', 'Character', 'Common'],
                ['BT1-006', 'Yamcha', 'Character', 'Common'],
                ['BT1-007', 'Chiaotzu', 'Character', 'Common'],
                ['BT1-008', 'Master Roshi', 'Character', 'Uncommon'],
                ['BT1-009', 'Oolong', 'Character', 'Common'],
                ['BT1-010', 'Launch', 'Character', 'Common'],
                ['BT1-011', 'Puar', 'Character', 'Common'],
                ['BT1-012', 'Android 18', 'Character', 'Rare'],
                ['BT1-013', 'Android 17', 'Character', 'Rare'],
                ['BT1-014', 'Android 16', 'Character', 'Uncommon'],
                ['BT1-015', 'Cell', 'Character', 'Super Rare'],
                ['BT1-016', 'Perfect Cell', 'Character', 'Ultra Rare'],
                ['BT1-017', 'Frieza', 'Leader', 'Super Rare'],
                ['BT1-018', 'Frieza, Emperor of the Universe', 'Character', 'Super Rare'],
                ['BT1-019', 'Zarbon', 'Character', 'Rare'],
                ['BT1-020', 'Dodoria', 'Character', 'Uncommon'],
                ['BT1-021', 'Ginyu', 'Character', 'Rare'],
                ['BT1-022', 'Recoome', 'Character', 'Uncommon'],
                ['BT1-023', 'Burter', 'Character', 'Common'],
                ['BT1-024', 'Jeice', 'Character', 'Common'],
                ['BT1-025', 'Guldo', 'Character', 'Common'],
                ['BT1-026', 'Vegeta', 'Leader', 'Super Rare'],
                ['BT1-027', 'Vegeta, Prince of Destruction', 'Character', 'Super Rare'],
                ['BT1-028', 'Nappa', 'Character', 'Rare'],
                ['BT1-029', 'Raditz', 'Character', 'Uncommon'],
                ['BT1-030', 'Piccolo', 'Character', 'Rare'],
                ['BT1-031', 'Super Saiyan God Son Goku', 'Character', 'Ultra Rare'],
                ['BT1-032', 'Super Saiyan Son Goku', 'Character', 'Super Rare'],
                ['BT1-033', 'Super Saiyan Vegeta', 'Character', 'Super Rare'],
                ['BT1-034', 'Super Saiyan Trunks', 'Character', 'Rare'],
                ['BT1-035', 'Super Saiyan Gohan', 'Character', 'Rare'],
                ['BT1-036', 'Gohan', 'Character', 'Uncommon'],
                ['BT1-037', 'Goten', 'Character', 'Common'],
                ['BT1-038', 'Trunks', 'Character', 'Common'],
                ['BT1-039', 'Gotenks', 'Character', 'Rare'],
                ['BT1-040', 'Kamehameha', 'Battle Card', 'Rare'],
                ['BT1-041', 'Final Flash', 'Battle Card', 'Uncommon'],
                ['BT1-042', 'Special Beam Cannon', 'Battle Card', 'Common'],
                ['BT1-043', 'Destructo Disc', 'Battle Card', 'Common'],
                ['BT1-044', 'Scouter', 'Extra Card', 'Common'],
                ['BT1-045', 'Dragon Ball', 'Extra Card', 'Rare'],
                ['BT1-046', 'Senzu Bean', 'Extra Card', 'Uncommon'],
            ],
            // BT2 - Union Force
            'Union Force' => [
                ['BT2-001', 'Son Goku, God of the Universe', 'Leader', 'Special Rare'],
                ['BT2-002', 'Vegeta, God of Destruction', 'Leader', 'Special Rare'],
                ['BT2-003', 'Beerus', 'Character', 'Super Rare'],
                ['BT2-004', 'Whis', 'Character', 'Rare'],
                ['BT2-005', 'Champa', 'Character', 'Rare'],
                ['BT2-006', 'Vados', 'Character', 'Rare'],
                ['BT2-007', 'Hit', 'Character', 'Super Rare'],
                ['BT2-008', 'Cabba', 'Character', 'Uncommon'],
                ['BT2-009', 'Botamo', 'Character', 'Common'],
                ['BT2-010', 'Auta Magetta', 'Character', 'Common'],
                ['BT2-011', 'Frost', 'Character', 'Rare'],
                ['BT2-012', 'Trunks, Hope of the Future', 'Character', 'Super Rare'],
                ['BT2-013', 'Golden Frieza', 'Character', 'Super Rare'],
                ['BT2-014', 'Goku Black', 'Character', 'Super Rare'],
                ['BT2-015', 'Zamasu', 'Character', 'Super Rare'],
                ['BT2-016', 'Fused Zamasu', 'Character', 'Ultra Rare'],
                ['BT2-017', 'Vegito', 'Character', 'Ultra Rare'],
                ['BT2-018', 'Gotenks', 'Character', 'Rare'],
                ['BT2-019', 'Son Goku', 'Character', 'Rare'],
                ['BT2-020', 'Vegeta', 'Character', 'Rare'],
                ['BT2-021', 'Piccolo', 'Character', 'Uncommon'],
                ['BT2-022', 'Trunks', 'Character', 'Super Rare'],
                ['BT2-023', 'Android 18', 'Character', 'Rare'],
                ['BT2-024', 'Android 17', 'Character', 'Rare'],
                ['BT2-025', 'Krillin', 'Character', 'Common'],
                ['BT2-026', 'Super Saiyan Blue Son Goku', 'Character', 'Special Rare'],
                ['BT2-027', 'Super Saiyan Blue Vegeta', 'Character', 'Special Rare'],
                ['BT2-028', 'Super Saiyan Rose Goku Black', 'Character', 'Special Rare'],
                ['BT2-029', 'Kamehameha', 'Battle Card', 'Rare'],
                ['BT2-030', 'God Kamehameha', 'Battle Card', 'Super Rare'],
            ],
            // BT3 - Cross Worlds
            'Cross Worlds' => [
                ['BT3-001', 'Son Goku, Awakened Beyond Super Saiyan', 'Leader', 'Special Rare'],
                ['BT3-002', 'Vegeta, Transcendent Evolution', 'Leader', 'Special Rare'],
                ['BT3-003', 'Gohan', 'Character', 'Super Rare'],
                ['BT3-004', 'Piccolo', 'Character', 'Rare'],
                ['BT3-005', 'Android 17', 'Character', 'Rare'],
                ['BT3-006', 'Android 18', 'Character', 'Rare'],
                ['BT3-007', 'Tien Shinhan', 'Character', 'Uncommon'],
                ['BT3-008', 'Krillin', 'Character', 'Common'],
                ['BT3-009', 'Yamcha', 'Character', 'Common'],
                ['BT3-010', 'Master Roshi', 'Character', 'Uncommon'],
                ['BT3-011', 'Goku Black', 'Leader', 'Special Rare'],
                ['BT3-012', 'Zamasu', 'Character', 'Super Rare'],
                ['BT3-013', 'Fused Zamasu', 'Character', 'Super Rare'],
                ['BT3-014', 'Black Goku', 'Character', 'Super Rare'],
                ['BT3-015', 'Future Trunks', 'Character', 'Super Rare'],
                ['BT3-016', 'Future Mai', 'Character', 'Uncommon'],
                ['BT3-017', 'Vegito', 'Character', 'Special Rare'],
                ['BT3-018', 'Son Goku', 'Character', 'Super Rare'],
                ['BT3-019', 'Vegeta', 'Character', 'Super Rare'],
                ['BT3-020', 'Beerus', 'Character', 'Rare'],
                ['BT3-021', 'Whis', 'Character', 'Uncommon'],
                ['BT3-022', 'Hit', 'Character', 'Rare'],
                ['BT3-023', 'Caulifla', 'Character', 'Rare'],
                ['BT3-024', 'Kale', 'Character', 'Rare'],
                ['BT3-025', 'Kefla', 'Character', 'Special Rare'],
                ['BT3-026', 'Jiren', 'Character', 'Special Rare'],
                ['BT3-027', 'Toppo', 'Character', 'Rare'],
                ['BT3-028', 'Dyspo', 'Character', 'Uncommon'],
                ['BT3-029', 'Super Saiyan Blue Evolved Vegeta', 'Character', 'Special Rare'],
                ['BT3-030', 'Ultra Instinct Son Goku', 'Character', 'Special Rare'],
            ],
            // BT4 - Colossal Warfare
            'Colossal Warfare' => [
                ['BT4-001', 'Gogeta, Warrior of Hope', 'Leader', 'Special Rare'],
                ['BT4-002', 'Vegito, Potara Fusion', 'Leader', 'Special Rare'],
                ['BT4-003', 'Gogeta', 'Character', 'Special Rare'],
                ['BT4-004', 'Vegito', 'Character', 'Special Rare'],
                ['BT4-005', 'Son Goku', 'Character', 'Super Rare'],
                ['BT4-006', 'Vegeta', 'Character', 'Super Rare'],
                ['BT4-007', 'Gohan', 'Character', 'Rare'],
                ['BT4-008', 'Piccolo', 'Character', 'Rare'],
                ['BT4-009', 'Android 17', 'Character', 'Rare'],
                ['BT4-010', 'Android 18', 'Character', 'Rare'],
                ['BT4-011', 'Cell', 'Leader', 'Special Rare'],
                ['BT4-012', 'Perfect Cell', 'Character', 'Special Rare'],
                ['BT4-013', 'Semi-Perfect Cell', 'Character', 'Super Rare'],
                ['BT4-014', 'Imperfect Cell', 'Character', 'Rare'],
                ['BT4-015', 'Cell Jr.', 'Character', 'Common'],
                ['BT4-016', 'Majin Buu', 'Leader', 'Special Rare'],
                ['BT4-017', 'Super Buu', 'Character', 'Special Rare'],
                ['BT4-018', 'Kid Buu', 'Character', 'Super Rare'],
                ['BT4-019', 'Evil Buu', 'Character', 'Rare'],
                ['BT4-020', 'Fat Buu', 'Character', 'Uncommon'],
                ['BT4-021', 'Babidi', 'Character', 'Rare'],
                ['BT4-022', 'Dabura', 'Character', 'Rare'],
                ['BT4-023', 'Spopovich', 'Character', 'Common'],
                ['BT4-024', 'Yamu', 'Character', 'Common'],
                ['BT4-025', 'Pui Pui', 'Character', 'Common'],
                ['BT4-026', 'Yakon', 'Character', 'Common'],
                ['BT4-027', 'Super Saiyan 3 Son Goku', 'Character', 'Special Rare'],
                ['BT4-028', 'Gotenks', 'Character', 'Super Rare'],
                ['BT4-029', 'Mystic Gohan', 'Character', 'Super Rare'],
                ['BT4-030', 'Kamehameha', 'Battle Card', 'Rare'],
            ],
            // BT5 - Miraculous Revival
            'Miraculous Revival' => [
                ['BT5-001', 'Broly, Legendary Super Saiyan', 'Leader', 'Special Rare'],
                ['BT5-002', 'Broly', 'Character', 'Special Rare'],
                ['BT5-003', 'Paragus', 'Character', 'Rare'],
                ['BT5-004', 'Cheelai', 'Character', 'Uncommon'],
                ['BT5-005', 'Lemo', 'Character', 'Common'],
                ['BT5-006', 'Son Goku', 'Character', 'Super Rare'],
                ['BT5-007', 'Vegeta', 'Character', 'Super Rare'],
                ['BT5-008', 'Gogeta', 'Character', 'Special Rare'],
                ['BT5-009', 'Frieza', 'Character', 'Rare'],
                ['BT5-010', 'Frieza, Emperor Revived', 'Leader', 'Special Rare'],
                ['BT5-011', 'Sorbet', 'Character', 'Uncommon'],
                ['BT5-012', 'Tagoma', 'Character', 'Uncommon'],
                ['BT5-013', 'Shisami', 'Character', 'Common'],
                ['BT5-014', 'Super Saiyan Blue Son Goku', 'Character', 'Special Rare'],
                ['BT5-015', 'Super Saiyan Blue Vegeta', 'Character', 'Special Rare'],
                ['BT5-016', 'Golden Frieza', 'Character', 'Special Rare'],
                ['BT5-017', 'Super Saiyan God Son Goku', 'Character', 'Super Rare'],
                ['BT5-018', 'Whis', 'Character', 'Rare'],
                ['BT5-019', 'Beerus', 'Character', 'Rare'],
                ['BT5-020', 'Android 18', 'Character', 'Rare'],
            ],
            // BT6 - Realm of the Gods
            'Realm of the Gods' => [
                ['BT6-001', 'Beerus, God of Destruction', 'Leader', 'Special Rare'],
                ['BT6-002', 'Whis, Angel Guide', 'Leader', 'Special Rare'],
                ['BT6-003', 'Beerus', 'Character', 'Secret Rare'],
                ['BT6-004', 'Whis', 'Character', 'Super Rare'],
                ['BT6-005', 'Champa', 'Character', 'Rare'],
                ['BT6-006', 'Vados', 'Character', 'Rare'],
                ['BT6-007', 'Rumsshi', 'Character', 'Rare'],
                ['BT6-008', 'Cus', 'Character', 'Uncommon'],
                ['BT6-009', 'Belmod', 'Character', 'Rare'],
                ['BT6-010', 'Marcarita', 'Character', 'Uncommon'],
                ['BT6-011', 'Son Goku', 'Character', 'Super Rare'],
                ['BT6-012', 'Vegeta', 'Character', 'Super Rare'],
                ['BT6-013', 'Broly', 'Character', 'Super Rare'],
                ['BT6-014', 'Hit', 'Character', 'Rare'],
                ['BT6-015', 'Jiren', 'Character', 'Super Rare'],
                ['BT6-016', 'Toppo', 'Character', 'Rare'],
                ['BT6-017', 'Dyspo', 'Character', 'Uncommon'],
                ['BT6-018', 'Frieza', 'Character', 'Rare'],
                ['BT6-019', 'Android 17', 'Character', 'Rare'],
                ['BT6-020', 'Gohan', 'Character', 'Rare'],
            ],
            // BT7 - Assault of the Saiyans
            'Assault of the Saiyans' => [
                ['BT7-001', 'Son Goku, Saiyan Raised on Earth', 'Leader', 'Special Rare'],
                ['BT7-002', 'Vegeta, Elite Warrior', 'Leader', 'Special Rare'],
                ['BT7-003', 'Son Goku', 'Character', 'Super Rare'],
                ['BT7-004', 'Vegeta', 'Character', 'Super Rare'],
                ['BT7-005', 'Gohan', 'Character', 'Rare'],
                ['BT7-006', 'Trunks', 'Character', 'Rare'],
                ['BT7-007', 'Goten', 'Character', 'Uncommon'],
                ['BT7-008', 'Pan', 'Character', 'Common'],
                ['BT7-009', 'Caulifla', 'Character', 'Super Rare'],
                ['BT7-010', 'Kale', 'Character', 'Super Rare'],
                ['BT7-011', 'Kefla', 'Character', 'Special Rare'],
                ['BT7-012', 'Cabba', 'Character', 'Rare'],
                ['BT7-013', 'Jiren', 'Character', 'Special Rare'],
                ['BT7-014', 'Toppo', 'Character', 'Rare'],
                ['BT7-015', 'Dyspo', 'Character', 'Uncommon'],
                ['BT7-016', 'Super Saiyan 2 Caulifla', 'Character', 'Super Rare'],
                ['BT7-017', 'Legendary Super Saiyan Kale', 'Character', 'Super Rare'],
                ['BT7-018', 'Ultra Instinct Son Goku', 'Character', 'Special Rare'],
                ['BT7-019', 'Super Saiyan Blue Son Goku', 'Character', 'Super Rare'],
                ['BT7-020', 'Super Saiyan Blue Vegeta', 'Character', 'Super Rare'],
            ],
            // BT8 - Malicious Machinations
            'Malicious Machinations' => [
                ['BT8-001', 'Android 21, the Mastermind', 'Leader', 'Special Rare'],
                ['BT8-002', 'Android 21', 'Character', 'Special Rare'],
                ['BT8-003', 'Android 21 (Good)', 'Character', 'Super Rare'],
                ['BT8-004', 'Android 16', 'Character', 'Rare'],
                ['BT8-005', 'Android 17', 'Character', 'Rare'],
                ['BT8-006', 'Android 18', 'Character', 'Rare'],
                ['BT8-007', 'Cell', 'Character', 'Rare'],
                ['BT8-008', 'Frieza', 'Character', 'Rare'],
                ['BT8-009', 'Nappa', 'Character', 'Uncommon'],
                ['BT8-010', 'Ginyu', 'Character', 'Uncommon'],
                ['BT8-011', 'Son Goku', 'Character', 'Super Rare'],
                ['BT8-012', 'Vegeta', 'Character', 'Super Rare'],
                ['BT8-013', 'Gohan', 'Character', 'Rare'],
                ['BT8-014', 'Krillin', 'Character', 'Uncommon'],
                ['BT8-015', 'Piccolo', 'Character', 'Rare'],
                ['BT8-016', 'Trunks', 'Character', 'Rare'],
                ['BT8-017', 'Ultra Instinct Son Goku', 'Character', 'Special Rare'],
                ['BT8-018', 'Super Saiyan Blue Son Goku', 'Character', 'Super Rare'],
                ['BT8-019', 'Super Saiyan Blue Vegeta', 'Character', 'Super Rare'],
                ['BT8-020', 'Golden Frieza', 'Character', 'Super Rare'],
            ],
        ];

        $imported = 0;
        foreach ($sets as $setName => $cards) {
            foreach ($cards as $card) {
                TcgCardCatalog::updateOrCreate(
                    ['card_number' => $card[0], 'tcg_category' => 'dragon_ball_super'],
                    [
                        'name'     => $card[1],
                        'set_name' => $setName,
                        'rarity'   => $card[3],
                    ]
                );
                $imported++;
            }
        }

        $this->command->info("✅ Dragon Ball Super: $imported carte importate!");
    }
}