<?php

namespace Database\Seeders;

use App\Models\TcgCardCatalog;
use Illuminate\Database\Seeder;

class OnePieceCardsSeeder extends Seeder
{
    public function run(): void
    {
        $sets = [
            // OP01 - Romance Dawn
            'Romance Dawn' => [
                ['OP01-001', 'Monkey D. Luffy', 'Leader', 'Secret Rare'],
                ['OP01-002', 'Roronoa Zoro', 'Character', 'Super Rare'],
                ['OP01-003', 'Nami', 'Character', 'Rare'],
                ['OP01-004', 'Usopp', 'Character', 'Common'],
                ['OP01-005', 'Sanji', 'Character', 'Rare'],
                ['OP01-006', 'Tony Tony Chopper', 'Character', 'Common'],
                ['OP01-007', 'Nico Robin', 'Character', 'Rare'],
                ['OP01-008', 'Franky', 'Character', 'Uncommon'],
                ['OP01-009', 'Brook', 'Character', 'Uncommon'],
                ['OP01-010', 'Jinbe', 'Character', 'Rare'],
                ['OP01-011', 'Shanks', 'Leader', 'Secret Rare'],
                ['OP01-012', 'Buggy', 'Character', 'Rare'],
                ['OP01-013', 'Coby', 'Character', 'Common'],
                ['OP01-014', 'Helmeppo', 'Character', 'Common'],
                ['OP01-015', 'Alvida', 'Character', 'Common'],
                ['OP01-016', 'Arlong', 'Character', 'Rare'],
                ['OP01-017', 'Smoker', 'Character', 'Rare'],
                ['OP01-018', 'Tashigi', 'Character', 'Uncommon'],
                ['OP01-019', 'Crocodile', 'Character', 'Super Rare'],
                ['OP01-020', 'Dracule Mihawk', 'Character', 'Super Rare'],
                ['OP01-021', 'Garp', 'Character', 'Super Rare'],
                ['OP01-022', 'Sengoku', 'Character', 'Rare'],
                ['OP01-023', 'Kizaru', 'Character', 'Rare'],
                ['OP01-024', 'Aokiji', 'Character', 'Rare'],
                ['OP01-025', 'Akainu', 'Character', 'Rare'],
                ['OP01-026', 'Whitebeard', 'Leader', 'Secret Rare'],
                ['OP01-027', 'Marco', 'Character', 'Super Rare'],
                ['OP01-028', 'Ace', 'Character', 'Super Rare'],
                ['OP01-029', 'Vista', 'Character', 'Uncommon'],
                ['OP01-030', 'Jozu', 'Character', 'Uncommon'],
                ['OP01-031', 'Izo', 'Character', 'Common'],
                ['OP01-032', 'Curiel', 'Character', 'Common'],
                ['OP01-033', 'Atmos', 'Character', 'Common'],
                ['OP01-034', 'Blamenco', 'Character', 'Common'],
                ['OP01-035', 'Blenheim', 'Character', 'Common'],
                ['OP01-036', 'Elmy', 'Character', 'Common'],
                ['OP01-037', 'Fossa', 'Character', 'Common'],
                ['OP01-038', 'Haruta', 'Character', 'Common'],
                ['OP01-039', 'Kingdew', 'Character', 'Common'],
                ['OP01-040', 'Namur', 'Character', 'Common'],
                ['OP01-041', 'Rakuyo', 'Character', 'Common'],
                ['OP01-042', 'Speed Jiru', 'Character', 'Common'],
                ['OP01-043', 'Thatch', 'Character', 'Uncommon'],
                ['OP01-044', 'Teach', 'Character', 'Super Rare'],
                ['OP01-045', 'Gum-Gum Pistol', 'Event', 'Common'],
                ['OP01-046', 'Gum-Gum Rocket', 'Event', 'Uncommon'],
                ['OP01-047', 'Gum-Gum Gatling', 'Event', 'Rare'],
                ['OP01-048', 'Gomu Gomu no Mi', 'Stage', 'Rare'],
                ['OP01-049', 'Thousand Sunny', 'Stage', 'Uncommon'],
                ['OP01-050', 'Moby Dick', 'Stage', 'Rare'],
            ],
            // OP02 - Paramount War
            'Paramount War' => [
                ['OP02-001', 'Portgas D. Ace', 'Leader', 'Secret Rare'],
                ['OP02-002', 'Whitebeard', 'Character', 'Secret Rare'],
                ['OP02-003', 'Marco', 'Character', 'Super Rare'],
                ['OP02-004', 'Jinbe', 'Character', 'Rare'],
                ['OP02-005', 'Squard', 'Character', 'Uncommon'],
                ['OP02-006', 'Little Oars Jr.', 'Character', 'Rare'],
                ['OP02-007', 'Daz Bonez', 'Character', 'Common'],
                ['OP02-008', 'Mr. 1', 'Character', 'Common'],
                ['OP02-009', 'Bentham', 'Character', 'Common'],
                ['OP02-010', 'Crocodile', 'Character', 'Super Rare'],
                ['OP02-011', 'Akainu', 'Character', 'Super Rare'],
                ['OP02-012', 'Aokiji', 'Character', 'Super Rare'],
                ['OP02-013', 'Kizaru', 'Character', 'Rare'],
                ['OP02-014', 'Sengoku', 'Character', 'Rare'],
                ['OP02-015', 'Garp', 'Character', 'Rare'],
                ['OP02-016', 'Coby', 'Character', 'Uncommon'],
                ['OP02-017', 'Helmeppo', 'Character', 'Common'],
                ['OP02-018', 'Smoker', 'Character', 'Rare'],
                ['OP02-019', 'Tashigi', 'Character', 'Uncommon'],
                ['OP02-020', 'Hancock', 'Leader', 'Secret Rare'],
                ['OP02-021', 'Boa Hancock', 'Character', 'Super Rare'],
                ['OP02-022', 'Marigold', 'Character', 'Uncommon'],
                ['OP02-023', 'Sandersonia', 'Character', 'Uncommon'],
                ['OP02-024', 'Marguerite', 'Character', 'Common'],
                ['OP02-025', 'Sweet Pea', 'Character', 'Common'],
                ['OP02-026', 'Aphelandra', 'Character', 'Common'],
                ['OP02-027', 'Ran', 'Character', 'Common'],
                ['OP02-028', 'Daisy', 'Character', 'Common'],
                ['OP02-029', 'Cosmos', 'Character', 'Common'],
                ['OP02-030', 'Belladonna', 'Character', 'Common'],
                ['OP02-031', 'Monkey D. Luffy', 'Character', 'Super Rare'],
                ['OP02-032', 'Roronoa Zoro', 'Character', 'Rare'],
                ['OP02-033', 'Nami', 'Character', 'Uncommon'],
                ['OP02-034', 'Usopp', 'Character', 'Common'],
                ['OP02-035', 'Sanji', 'Character', 'Rare'],
                ['OP02-036', 'Marineford', 'Stage', 'Rare'],
                ['OP02-037', 'Amazon Lily', 'Stage', 'Uncommon'],
                ['OP02-038', 'Clima-Tact', 'Event', 'Common'],
                ['OP02-039', 'Hiken', 'Event', 'Rare'],
                ['OP02-040', 'Magu Magu no Mi', 'Stage', 'Super Rare'],
            ],
            // OP03 - Pillars of Strength
            'Pillars of Strength' => [
                ['OP03-001', 'Trafalgar Law', 'Leader', 'Secret Rare'],
                ['OP03-002', 'Bepo', 'Character', 'Uncommon'],
                ['OP03-003', 'Jean Bart', 'Character', 'Common'],
                ['OP03-004', 'Penguin', 'Character', 'Common'],
                ['OP03-005', 'Shachi', 'Character', 'Common'],
                ['OP03-006', 'Boa Hancock', 'Leader', 'Secret Rare'],
                ['OP03-007', 'Marigold', 'Character', 'Rare'],
                ['OP03-008', 'Sandersonia', 'Character', 'Rare'],
                ['OP03-009', 'Elder Nyon', 'Character', 'Uncommon'],
                ['OP03-010', 'Enel', 'Leader', 'Secret Rare'],
                ['OP03-011', 'Ohm', 'Character', 'Rare'],
                ['OP03-012', 'Satori', 'Character', 'Uncommon'],
                ['OP03-013', 'Shura', 'Character', 'Uncommon'],
                ['OP03-014', 'Gedatsu', 'Character', 'Uncommon'],
                ['OP03-015', 'Hotori', 'Character', 'Common'],
                ['OP03-016', 'Kotori', 'Character', 'Common'],
                ['OP03-017', 'Yama', 'Character', 'Common'],
                ['OP03-018', 'Donquixote Doflamingo', 'Leader', 'Secret Rare'],
                ['OP03-019', 'Sugar', 'Character', 'Super Rare'],
                ['OP03-020', 'Trebol', 'Character', 'Rare'],
                ['OP03-021', 'Diamante', 'Character', 'Rare'],
                ['OP03-022', 'Pica', 'Character', 'Rare'],
                ['OP03-023', 'Gladius', 'Character', 'Uncommon'],
                ['OP03-024', 'Baby 5', 'Character', 'Uncommon'],
                ['OP03-025', 'Buffalo', 'Character', 'Common'],
                ['OP03-026', 'Giolla', 'Character', 'Common'],
                ['OP03-027', 'Lao G', 'Character', 'Common'],
                ['OP03-028', 'Machvise', 'Character', 'Common'],
                ['OP03-029', 'Monkey D. Luffy', 'Character', 'Super Rare'],
                ['OP03-030', 'Roronoa Zoro', 'Character', 'Super Rare'],
                ['OP03-031', 'Nami', 'Character', 'Rare'],
                ['OP03-032', 'Usopp', 'Character', 'Uncommon'],
                ['OP03-033', 'Sanji', 'Character', 'Rare'],
                ['OP03-034', 'Tony Tony Chopper', 'Character', 'Common'],
                ['OP03-035', 'Nico Robin', 'Character', 'Rare'],
                ['OP03-036', 'Franky', 'Character', 'Uncommon'],
                ['OP03-037', 'Skypiea', 'Stage', 'Rare'],
                ['OP03-038', 'Dressrosa', 'Stage', 'Rare'],
                ['OP03-039', 'Ope Ope no Mi', 'Stage', 'Super Rare'],
                ['OP03-040', 'Pika Pika no Mi', 'Stage', 'Rare'],
            ],
            // OP04 - Kingdoms of Intrigue
            'Kingdoms of Intrigue' => [
                ['OP04-001', 'Monkey D. Luffy', 'Leader', 'Secret Rare'],
                ['OP04-002', 'Roronoa Zoro', 'Character', 'Super Rare'],
                ['OP04-003', 'Nami', 'Character', 'Rare'],
                ['OP04-004', 'Usopp', 'Character', 'Common'],
                ['OP04-005', 'Sanji', 'Character', 'Rare'],
                ['OP04-006', 'Tony Tony Chopper', 'Character', 'Common'],
                ['OP04-007', 'Nico Robin', 'Character', 'Rare'],
                ['OP04-008', 'Franky', 'Character', 'Uncommon'],
                ['OP04-009', 'Brook', 'Character', 'Uncommon'],
                ['OP04-010', 'Jinbe', 'Character', 'Rare'],
                ['OP04-011', 'Kaido', 'Leader', 'Secret Rare'],
                ['OP04-012', 'Big Mom', 'Leader', 'Secret Rare'],
                ['OP04-013', 'Yamato', 'Character', 'Super Rare'],
                ['OP04-014', 'Ulti', 'Character', 'Rare'],
                ['OP04-015', 'Page One', 'Character', 'Uncommon'],
                ['OP04-016', 'Who\'s Who', 'Character', 'Rare'],
                ['OP04-017', 'Black Maria', 'Character', 'Rare'],
                ['OP04-018', 'Sasaki', 'Character', 'Rare'],
                ['OP04-019', 'Queen', 'Character', 'Super Rare'],
                ['OP04-020', 'King', 'Character', 'Super Rare'],
                ['OP04-021', 'Jack', 'Character', 'Rare'],
                ['OP04-022', 'Charlotte Katakuri', 'Character', 'Super Rare'],
                ['OP04-023', 'Charlotte Cracker', 'Character', 'Rare'],
                ['OP04-024', 'Charlotte Smoothie', 'Character', 'Rare'],
                ['OP04-025', 'Perospero', 'Character', 'Uncommon'],
                ['OP04-026', 'Oven', 'Character', 'Uncommon'],
                ['OP04-027', 'Daifuku', 'Character', 'Uncommon'],
                ['OP04-028', 'Compote', 'Character', 'Common'],
                ['OP04-029', 'Wano Country', 'Stage', 'Rare'],
                ['OP04-030', 'Whole Cake Island', 'Stage', 'Rare'],
            ],
            // OP05 - Awakening of the New Era
            'Awakening of the New Era' => [
                ['OP05-001', 'Blackbeard', 'Leader', 'Secret Rare'],
                ['OP05-002', 'Shiryu', 'Character', 'Super Rare'],
                ['OP05-003', 'Burgess', 'Character', 'Rare'],
                ['OP05-004', 'Laffitte', 'Character', 'Rare'],
                ['OP05-005', 'Doc Q', 'Character', 'Uncommon'],
                ['OP05-006', 'Avalo Pizarro', 'Character', 'Uncommon'],
                ['OP05-007', 'Sanjuan Wolf', 'Character', 'Uncommon'],
                ['OP05-008', 'Vasco Shot', 'Character', 'Common'],
                ['OP05-009', 'Catalina Devon', 'Character', 'Common'],
                ['OP05-010', 'Jewelry Bonney', 'Leader', 'Secret Rare'],
                ['OP05-011', 'Basil Hawkins', 'Character', 'Rare'],
                ['OP05-012', 'X Drake', 'Character', 'Rare'],
                ['OP05-013', 'Eustass Kid', 'Leader', 'Secret Rare'],
                ['OP05-014', 'Killer', 'Character', 'Rare'],
                ['OP05-015', 'Heat', 'Character', 'Uncommon'],
                ['OP05-016', 'Wire', 'Character', 'Common'],
                ['OP05-017', 'Monkey D. Luffy', 'Character', 'Super Rare'],
                ['OP05-018', 'Roronoa Zoro', 'Character', 'Super Rare'],
                ['OP05-019', 'Nami', 'Character', 'Rare'],
                ['OP05-020', 'Sanji', 'Character', 'Rare'],
            ],
            // OP06 - Wings of the Captain
            'Wings of the Captain' => [
                ['OP06-001', 'Roronoa Zoro', 'Leader', 'Secret Rare'],
                ['OP06-002', 'Sanji', 'Leader', 'Secret Rare'],
                ['OP06-003', 'Monkey D. Luffy', 'Character', 'Super Rare'],
                ['OP06-004', 'Nami', 'Character', 'Rare'],
                ['OP06-005', 'Usopp', 'Character', 'Common'],
                ['OP06-006', 'Tony Tony Chopper', 'Character', 'Common'],
                ['OP06-007', 'Nico Robin', 'Character', 'Rare'],
                ['OP06-008', 'Franky', 'Character', 'Uncommon'],
                ['OP06-009', 'Brook', 'Character', 'Uncommon'],
                ['OP06-010', 'Jinbe', 'Character', 'Rare'],
                ['OP06-011', 'Lucci', 'Character', 'Super Rare'],
                ['OP06-012', 'Kaku', 'Character', 'Rare'],
                ['OP06-013', 'Stussy', 'Character', 'Rare'],
                ['OP06-014', 'Luffy Gear 5', 'Character', 'Secret Rare'],
                ['OP06-015', 'Luffy Gear 4', 'Character', 'Super Rare'],
                ['OP06-016', 'Zoro Ashura', 'Character', 'Super Rare'],
                ['OP06-017', 'Sanji Diable Jambe', 'Character', 'Super Rare'],
                ['OP06-018', 'Nami Zeus', 'Character', 'Rare'],
                ['OP06-019', 'Usopp Sniper King', 'Character', 'Rare'],
                ['OP06-020', 'Robin Gigante', 'Character', 'Rare'],
            ],
        ];

        $imported = 0;
        foreach ($sets as $setName => $cards) {
            foreach ($cards as $card) {
                TcgCardCatalog::updateOrCreate(
                    ['card_number' => $card[0], 'tcg_category' => 'onepiece'],
                    [
                        'name'     => $card[1],
                        'set_name' => $setName,
                        'rarity'   => $card[3],
                    ]
                );
                $imported++;
            }
        }

        $this->command->info("✅ One Piece: $imported carte importate!");
    }
}